using Test, GraphCombinations
import GraphCombinations as GC

sort_graph_results(results) = sort(results; by=first)

function direct_halfedge_degrees(graph, num_vertices)
    degrees = zeros(Int, num_vertices)
    for edge in graph
        degrees[edge.first] += 1
        degrees[edge.second] += 1
    end
    return degrees
end

function direct_degree_sequence(n)
    degrees = Int[]
    for (degree, count) in enumerate(n)
        append!(degrees, fill(degree, count))
    end
    return degrees
end

@testset "Direct multigraph generation" begin
    # Match the independent Wick oracle over the same exhaustive small-degree domain.
    specifications = Vector{Vector{Int}}()
    for n1 in 0:2, n2 in 0:2, n3 in 0:2, n4 in 0:2
        n = [n1, n2, n3, n4]
        degree = total_degree(n)
        iseven(degree) && 0 < degree <= 8 && sum(n[2:end]) <= 4 && push!(specifications, n)
    end

    for n in specifications
        direct_all = GC._allgraphs_direct(n; connected=false)
        reference_all = GC._allgraphs_wick_reference(n; connected=false)
        @test direct_all == sort_graph_results(reference_all)
        @test issorted(direct_all; by=first)

        direct_connected = GC._allgraphs_direct(n; connected=true)
        reference_connected = GC._allgraphs_wick_reference(n; connected=true)
        @test direct_connected == sort_graph_results(reference_connected)
        @test issorted(direct_connected; by=first)

        num_vertices = sum(n)
        expected_degrees = direct_degree_sequence(n)
        normalization = combinatoric_factor(n)
        vertex_permutations = GC._internal_vertex_permutation_factor(n)

        # The orbit sizes reconstructed from the final symmetry denominators must account for
        # every degree-labelled multigraph generated by the residual-degree recursion.
        reconstructed_labeled = big(0)
        reconstructed_pairings = big(0)
        for (graph, symmetry_denominator) in direct_all
            @test sort(direct_halfedge_degrees(graph, num_vertices)) ==
                sort(expected_degrees)

            edge_factor = GC._edge_symmetry_factor(graph)
            automorphisms, remainder = divrem(symmetry_denominator, edge_factor)
            @test iszero(remainder)
            @test iszero(rem(vertex_permutations, automorphisms))
            reconstructed_labeled += vertex_permutations ÷ automorphisms

            @test iszero(rem(normalization, symmetry_denominator))
            reconstructed_pairings += normalization ÷ symmetry_denominator
        end

        @test reconstructed_labeled == GC._count_labeled_multigraphs(n)
        @test reconstructed_pairings == prod(big(k) for k in 1:2:(total_degree(n) - 1))
    end

    # Candidate-space regression checks for the phi^4 two-point function. The corresponding
    # Wick spaces contain 5!!, 9!!, 13!!, 17!! and 21!! pairings, respectively.
    @test GC._count_labeled_multigraphs([2, 0, 0, 1]) == 2
    @test GC._count_labeled_multigraphs([2, 0, 0, 2]) == 11
    @test GC._count_labeled_multigraphs([2, 0, 0, 3]) == 96
    @test GC._count_labeled_multigraphs([2, 0, 0, 4]) == 1326
    @test GC._count_labeled_multigraphs([2, 0, 0, 5]) == 26451

    # Direct connected topology counts through the original order-four acceptance target.
    @test length(GC._allgraphs_direct([2, 0, 0, 1])) == 1
    @test length(GC._allgraphs_direct([2, 0, 0, 2])) == 3
    @test length(GC._allgraphs_direct([2, 0, 0, 3])) == 10
    @test length(GC._allgraphs_direct([2, 0, 0, 4])) == 39

    # Stress the direct path one order beyond the acceptance target without asking Wick to
    # materialize 21!! = 13,749,310,575 pairings. The exact symmetry denominators must still
    # reconstruct the complete pairing count over all connected and disconnected topologies.
    order5 = [2, 0, 0, 5]
    order5_results = GC._allgraphs_direct(order5; connected=false)
    order5_normalization = combinatoric_factor(order5)
    order5_pairings = sum(
        order5_normalization ÷ symmetry for (_, symmetry) in order5_results
    )
    @test order5_pairings == prod(big(k) for k in 1:2:(total_degree(order5) - 1))
end
